'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,CheckCheck,ScanLine,Square} from 'lucide-react';
import jsQR from 'jsqr';
type Receipt={name:string;nis:string;nisn?:string;gender?:string;className:string;status:string;time:string;duplicate?:boolean};
export default function QRScanner({ready,hasStudents,onRecorded}:{ready:boolean;hasStudents:boolean;onRecorded:()=>Promise<void>}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),epoch=useRef(0),callback=useRef(onRecorded),seen=useRef(new Set<string>()),lastToken=useRef(''),missingSince=useRef(0),mounted=useRef(true);
 callback.current=onRecorded;
 const [active,setActive]=useState(false),[working,setWorking]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null),[count,setCount]=useState(0);
 function shutdown(){epoch.current++;if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;}
 function stop(){shutdown();setActive(false);setStarting(false);}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;shutdown();};},[]);
 function locate():Promise<{latitude:number;longitude:number;accuracy:number;timestamp:number}>{return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('Browser tidak mendukung lokasi.'));navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp}),e=>reject(Error(e.code===1?'Izinkan akses lokasi untuk mencatat kehadiran.':'Lokasi belum tersedia. Aktifkan GPS dan coba di area terbuka.')),{enableHighAccuracy:true,maximumAge:0,timeout:20000});});}
 async function start(){shutdown();const version=epoch.current;setError('');setStarting(true);seen.current.clear();lastToken.current='';try{if(!ready)throw Error('Atur lokasi sekolah terlebih dahulu.');if(!hasStudents)throw Error('Tambahkan data siswa terlebih dahulu.');if(!navigator.mediaDevices?.getUserMedia)throw Error('Kamera tidak tersedia. Gunakan browser dengan akses kamera.');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:960},height:{ideal:720}},audio:false});if(!mounted.current||version!==epoch.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;video.current!.srcObject=s;await video.current!.play();if(version!==epoch.current)return;setActive(true);tick(version);}catch(e){if(mounted.current&&version===epoch.current){shutdown();setActive(false);setError((e as Error).name==='NotAllowedError'?'Izin kamera ditolak. Aktifkan izin kamera pada browser.':(e as Error).message);}}finally{if(mounted.current)setStarting(false);}}
 async function record(token:string,version:number){setWorking(true);setError('');setReceipt(null);try{
 if(!/^SANJARA:[a-f0-9-]{36}$/.test(token))throw Error('QR ini bukan kartu siswa SANJARA.');const location=await locate();if(version!==epoch.current)return;
 const response=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'attendance',method:'QR',token,location})});const result=await response.json() as {error?:string;receipt?:Receipt};
 if(response.ok||response.status===409&&result.receipt){seen.current.add(token);if(mounted.current){setReceipt({...result.receipt!,duplicate:response.status===409});if(response.ok)setCount(n=>n+1);}await callback.current();}else throw Error(result.error||'Penyimpanan gagal. Periksa rekap sebelum mencoba kembali.');
 }catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setWorking(false);if(version===epoch.current)timer.current=setTimeout(()=>tick(version),1200);}}
 function tick(version:number){if(version!==epoch.current)return;const v=video.current;if(v&&v.readyState>=2&&v.videoWidth){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=Math.round(v.videoHeight/v.videoWidth*640);const ctx=canvas.getContext('2d',{willReadFrequently:true});if(ctx){ctx.drawImage(v,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const found=jsQR(pixels.data,canvas.width,canvas.height);if(found){missingSince.current=0;if(found.data!==lastToken.current&&!seen.current.has(found.data)){lastToken.current=found.data;void record(found.data,version);return;}}else{if(!missingSince.current)missingSince.current=Date.now();if(Date.now()-missingSince.current>800)lastToken.current='';}}}timer.current=setTimeout(()=>tick(version),250);}
 return <div><div className="scanner-status"><span><i className={active?'live':''}/>{working?'Memeriksa lokasi & menyimpan…':active?'Pemindai aktif · tunjukkan kartu berikutnya':'Siap memulai pemindaian'}</span><b>{count} tercatat</b></div><div className="camera-box"><video ref={video} playsInline muted className={active?'visible-video':''}/>{!active&&<div className="camera-placeholder"><ScanLine size={48}/><span>Sekali aktifkan, kartu dibaca otomatis</span></div>}{active&&<div className="scan-frame"/>}</div>{error&&<div role="alert" className="alert scanner-message">{error}<small>Jauhkan kartu dari kamera, lalu arahkan kembali untuk mencoba ulang.</small></div>}{receipt&&<div role="status" className={'scan-receipt '+(receipt.duplicate?'duplicate':'')}><CheckCheck size={27}/><div><small>{receipt.duplicate?'SUDAH TERCATAT HARI INI':'KEHADIRAN TERSIMPAN'}</small><h3>{receipt.name}</h3><p>NIPD {receipt.nis} · NISN {receipt.nisn||'—'} · {receipt.className}</p><b>{receipt.status} · {new Date(receipt.time).toLocaleTimeString('id-ID',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit'})} WIB</b></div></div>}<div className="button-row">{!active?<button disabled={starting||working||!ready||!hasStudents} className="primary full" onClick={start}><Camera size={17}/>{starting?'Mengaktifkan kamera…':'Mulai scan otomatis'}</button>:<button className="secondary full" disabled={working} onClick={stop}><Square size={15}/>Hentikan pemindai</button>}</div><p className="helper">{!ready?'Atur lokasi sekolah terlebih dahulu.':!hasStudents?'Tambahkan siswa terlebih dahulu.':'Setelah tersimpan, langsung lanjut ke siswa berikutnya. Kartu yang sama tidak dicatat dua kali.'}</p></div>;
}
